lib/0304/print_hello.dart, lib/0305/01_team_study.dart, lib/0305/02_team_study.dart, lib/0305/03_team_study.dart, lib/0307/cleric.dart, lib/0307/hero.dart, lib/0307/slime.dart, lib/0308/00_memory.dart, lib/0308/02_constructor.dart, lib/0308/hero.dart, lib/0308/sword.dart, lib/0308/wizard.dart
0308 Cleric class를 수정
- maxHp, maxMP field에 static 키워드를 추가 하였습니다.
- 생성자 parameter type을 수정하였습니다.
=> 240308_19_유지영 Cleric 클래스 수정

lib/24_03_08/cleric.dart
직업 클레릭에 대한 클래스 생성자 오버로드 추가
+ maxHp, maxMp 필드에 static 구문 추가
+ 생성자에 네임드 파라미터, 초기화 리스트 이용하여 생성자 변경
=> 240308_12_성종호

lib/240307/cleric.dart, lib/240307/main.dart
feat : 성직자 인스턴스 정의 및 여러 생성자 생성
성직자 기본
아서스 hp : 40 mp : 5
아서스2 hp : 35 mp : 기본값
아서스3 hp : 기본값 mp : 기본값
=> 340308_34_한정은

lib/02_03_08/sword.dart, lib/24_03-07/cleric.dart, lib/24_03-07/main.dart
=> 240308_16_신승찬 다트 파일 작성

lib/24_03_07/cleric.dart, lib/24_03_08/cleric.dart, lib/24_03_08/main.dart
**Cleric  클래스 수정**
- static 필드 추가
- HP와 MP는 Named parrameter로 지정
=> 240308_08_박세훈

lib/24_03_07/cleric.dart, lib/24_03_07/hero.dart, lib/24_03_07/main.dart, lib/24_03_07/sword.dart, lib/24_03_07/wizard.dart, lib/24_03_08/00_memory.dart, lib/24_03_08/01_sword.dart, lib/24_03_08/02_constructor.dart, lib/24_03_08/03_static.dart
● 생성자의 파라미터와 static, const의 관계
● 메모리 주소에 대한 이해
=> 240308_32_최지원

lib/24_03_07/cleric.dart
=> 240308_06_김형민 연습문제

lib/240307/240307.dart, lib/240308/240308_problem1.dart, lib/240308/240308_problem2.dart
=> 240308_04_김윤아

lib/240307/cleric.dart
feat static final change to static const 
static final change to static const
=> 240308_15_송진섭

lib/24_03_07/cleric.dart
- 240307 직전 PR 리뷰 반영 (this 제거)
- Cleric static 타입 필드 추가
- Cleric 생성자 변경
-  required 사용 - name 필드 필수입력
-  hp, mp 기본값 할당
=> 240308_25_전성수

lib/0305/03_team_study.dart, lib/0307/cleric.dart, lib/0308/00_memory.dart, lib/0308/hero.dart
- 클래릭 클래스를 수정하였습니다.
- static const와 final 차이에 대해
=> 240308_19_유지영 클래스 수정

lib/230307/cleric.dart, lib/240307/cleric.dart, lib/240308/cleric2.dart
Optional Parameter 활용하여 아서스 생성자 추가
=> 240308_10_변희선

lib/24_03_07/cleric.dart, lib/24_03_07/main.dart, lib/algorithm/question_01.dart, lib/algorithm/question_02.dart, lib/algorithm/question_03.dart, lib/algorithm/question_04.dart, lib/algorithm/question_05.dart, lib/algorithm/question_06.dart, lib/algorithm/question_07.dart, lib/algorithm/question_08_notyet.dart, lib/algorithm/question_09.dart, lib/algorithm/question_10.dart
- named parameter 를 사용한 생성자 변경하기
- 알고리즘 문제 풀이 폴더 병합
- 알고리즘 문제 8번.. 어떻게 풀어야 좋을까요.. 고민고민.. 
----
> ### 연습문제 1
Cleric클래스에 관하여, 2가지 수정을 하시오
현시점의 Cleric 클래스의 정의에는, 각 인스턴스별로 최대 HP와 최대 MP 필드에 대한 정보를 가지고 있다. 하지만, 모든 성직자의 최대 HP 는 50, 최대 MP 는 10으로 정해져 있어, 각 인스턴스가 각각의 정보를 가지는 것은 메모리 낭비이다. 
그래서, 최대 HP, 최대 MP의 필드가 공유 되도록 
필드 선언에 적절한 키워드를 추가하시오
----  
> ### 연습문제2
아래의 방침에 따라, 생성자를 추가 하시오
a) 이 클래스는 Cleric(“아서스", hp: 40, mp: 5) 와 같이, 이름, HP, MP 를 지정하여 인스턴스화 할 수 있다
b) 이 클래스는 Cleric(“아서스", hp: 35) 와 같이, 이름과 HP만으로 지정하여 인스턴스화 할 수 있다. 이 때, MP는 최대 MP와 같은 값이 초기화 된다
c) 이 클래스는 Cleric(“아서스") 와 같이 이름만을 지정하여 인스턴스화 할 수 있다. 이 때, HP 와 MP 는 최대 HP와 최대 MP로 초기화 된다
d) 이 클래스는 Cleric() 과 같이 이름을 지정하지 않는 경우에는 인스턴스화 할 수 없다고 한다. (이름이 없는 성직자는 존재 할 수 없음)
생성자는 가능한 한 중복되는 코드가 없도록 작성한다
=> 240308_14_송윤지

.gitignore, lib/24_03_08/cleric.dart
다음주가 되기 전에 함수 호출 시 parameter 전달이 머릿속에서 버벅이지 않게 많은 연습을 하자.
=> 240308_07_박상준

lib/24_03_07/cleric.dart, lib/24_03_07/hero.dart, lib/24_03_07/swrod.dart, lib/24_03_07/wizard.dart, lib/24_03_08/00_memory.dart, lib/24_03_08/01_sword.dart, lib/24_03_08/constructor.dart
**5일차 연습문제**
>연습문제 1번, 2번
- 4일차 연습문제의 Cleric 클래스에 생성자조건을 추가
- Named Parameter를 추가하여 순서에 상관없이 매핑
=> 240308_03_김세진

lib/24_03_08/cleric2.dart
- 연습문제 1번: 최대 HP, 최대 MP의 필드가 공유(static)
- 연습문제 2번: 생성자 추가
=> 240308_13_성효정 

lib/240307/cleric.dart, lib/240311/person.dart, lib/240311/wand.dart, lib/240311/wizard.dart, test/240311/wand_test.dart
feat1 : Wizard, Wand 클래스 정의 및 오류시 에러 문구 노출(Expection)
조건
마법사, 지팡이 이름 3자 이상
마법사 mp는 0 이하일 시 문구 노출
마법사 hp는 0 이하일 시 0으로 설정
지팡이 power은 0.5 이상 100 이하
feat2 : persom 클래스 생성 및 출생년도에 따른 나이 계산
=> 240311_34_한정은

lib/24_03_11/01_wizard.dart, lib/24_03_11/02_wand.dart, lib/24_03_11/03_Person.dart, test/24_03_11/01_wizard.dart, test/24_03_11/02_wand.dart
**Wizard, Wand 클래스 생성**
- Private, get, set 함수 사용하여 test 작성하기
**Person 클래스 생성**
- get 함수 사용하여 나이 구하기
=> 240311_03_김세진

lib/24_03_11/person.dart, lib/24_03_11/wand.dart, lib/24_03_11/wizard.dart, test/24_03_11/person_test.dart, test/24_03_11/wand_test.dart, test/24_03_11/wizard_test.dart
- Test case 작성
- getter & setter 활용
- 다양한 생성자 연습 & 적용
=> 230311_25_전성수

lib/24_03_07/wand.dart, lib/24_03_07/wizard.dart, lib/24_03_11/person_collection.dart, lib/24_03_11/person_encapsulation.dart, test/24_03_07/cleric_test.dart, test/24_03_07/wand_test.dart, test/24_03_07/wizard_test.dart, test/24_03_11/person_collection_test.dart, test/24_03_11/person_encapulation_test.dart
wizard, wand, person 클래스 추가
테스트 코드 추가
=> 240311_06_김형민 과제

lib/24_03_07/00_main.dart, lib/24_03_07/01_cleric.dart, lib/24_03_11/00_main.dart, lib/24_03_11/01_wizard.dart, lib/24_03_11/02_person.dart, lib/24_03_11/03_collection.dart, test/24_03_07/01_cleric_test.dart, test/24_03_11/01_wizard_test.dart, test/24_03_11/02_person_test.dart
#feat: collection 및 연습문제
- test code
- encapsulation
- collection
- 연습문제
=> 240311_22_이필립

lib/240311/_main.dart, lib/240311/person.dart, lib/240311/wand.dart, lib/240311/wizard.dart, pubspec.lock, test/240307/cleric_test.dart, test/240311/person_test.dart, test/240311/wand_test.dart, test/240311/wizard_test.dart
Wizard 클래스
- name vaildation 프로퍼티 정의
- hp vaildation 프로퍼티 정의
- mp vaildation 프로퍼티 정의
Wand 클래스
- name vaildation 프로퍼티 정의
- power vaildation 프로퍼티 정의
Person 클래스
- age 계산 프로퍼티 정의
- Wizard, Wand, Person 클래스에 대한 테스트 코드 작성
=> 240311_01_김동혁 캡슐화 컬렉션

lib/24_03_07/inn.dart, lib/24_03_07/king.dart, lib/24_03_07/wand.dart, lib/24_03_07/wizard.dart, lib/24_03_11/00_collection.dart, lib/24_03_11/01_person.dart, test/ldt_test.dart
● private 멤버를 다루고 getter, setter를 이용하여 private 멤버 변수를 컨트롤한다. 
● List, Set, Map 컬렉션에 대한 이해
● 테스트 코드 작성
=> 240311_32_최지원

lib/24_03_12/animal.dart, lib/24_03_12/shape.dart, lib/24_03_12/vehicle.dart, lib/practice/hero.dart, lib/practice/library.dart, lib/practice/slime.dart, lib/uml/animal.puml, lib/uml/hero.puml, lib/uml/library.puml, lib/uml/shape.puml, lib/uml/slime.puml, lib/uml/vehicle.puml
=> 240312_27_전종현

lib/240312/animal/animal.dart, lib/240312/animal/animal.plantuml, lib/240312/animal/bird.dart, lib/240312/animal/cat.dart, lib/240312/animal/dog.dart, lib/240312/book/book.dart, lib/240312/book/book.plantuml, lib/240312/book/ficton.dart, lib/240312/book/non_fiction.dart, lib/240312/rectangle/point.dart, lib/240312/rectangle/rectangle.dart, lib/240312/rectangle/rectangle.plantuml, lib/240312/slime/hero.dart, lib/240312/slime/poisonslime.dart, lib/240312/slime/slime.dart, lib/240312/slime/slime.plantuml, lib/240312/vehicle/car.dart, lib/240312/vehicle/motorcycle.dart, lib/240312/vehicle/truck.dart, lib/240312/vehicle/vehicle.dart, lib/240312/vehicle/vehicle.plantuml, lib/class_diagram.plantuml, lib/test/240312/animal_test.dart, lib/test/240312/poisonslime.dart, lib/test/240312/rectangle_test.dart, lib/test/240312/vehicle_test.dart
과제 
- 슬라임, 동물, 이동수단, 책, 사각형 추가
- UML추가
=> 240312_35_황태욱

lib/240312/Inherit/Rectangle.dart, lib/240312/Inherit/animal.dart, lib/240312/Inherit/bird.dart, lib/240312/Inherit/book.dart, lib/240312/Inherit/car.dart, lib/240312/Inherit/cat.dart, lib/240312/Inherit/diagrams/Animal.puml, lib/240312/Inherit/diagrams/Book.puml, lib/240312/Inherit/diagrams/PoisonSlime.puml, lib/240312/Inherit/diagrams/Rectangle.puml, lib/240312/Inherit/diagrams/Vehicle.puml, lib/240312/Inherit/dog.dart, lib/240312/Inherit/fiction.dart, lib/240312/Inherit/hero.dart, lib/240312/Inherit/motorcycle.dart, lib/240312/Inherit/nonFiction.dart, lib/240312/Inherit/point.dart, lib/240312/Inherit/poisonSlime.dart, lib/240312/Inherit/slime.dart, lib/240312/Inherit/truck.dart, lib/240312/Inherit/vehicle.dart, test/240312/Inherit/test_animal.dart, test/240312/Inherit/test_book.dart, test/240312/Inherit/test_psisonSlime.dart, test/240312/Inherit/test_rectangle.dart, test/240312/Inherit/test_vehicle.dart
create 7일차 과제
상속관련 문제 및 다이어그램 작성
=> 240312_15_송진섭

lib/24_03_11/01_wizard.dart, lib/24_03_11/02_person.dart, lib/24_03_11/02_wand.dart, lib/24_03_11/03_collection.dart, lib/24_03_11/04_person.dart, lib/24_03_12/00_main.dart, lib/24_03_12/01_hero.dart, lib/24_03_12/02_superHero.dart, lib/24_03_12/03_slime.dart, lib/24_03_12/04_poisonSlime.dart, lib/24_03_12/05_animal.dart, lib/24_03_12/05_animal.puml, lib/24_03_12/06_vehicle.dart, lib/24_03_12/06_vehicle.puml, lib/24_03_12/07_book.dart, lib/24_03_12/07_book.puml, lib/24_03_12/08_point.dart, lib/24_03_12/08_point.puml, test/24_03_11/01_wizard_test.dart, test/24_03_11/02_person_test.dart, test/24_03_12/02_superHero_test.dart, test/24_03_12/04_poisonSlime_test.dart, test/24_03_12/05_animal_test.dart, test/24_03_12/08_point_test.dart
#feat: 상속 및 클래스 나누기
- 하나의 파일에 몰려있던 클래스 분리
- slime
- 각종 uml
=> 240312_22_이필립

lib/240311/person.dart, lib/240311/person_collection.dart, lib/240311/wizard.dart, lib/240312/animal.puml, lib/240312/hero.dart, lib/240312/library.puml, lib/240312/point.puml, lib/240312/poison_slime.dart, lib/240312/slime.dart, lib/240312/super_hero.dart, lib/240312/vehicle.puml, test/240311/person_class_test.dart, test/240311/wand_test.dart, test/240312/attackhero.dart
feat1 : Create Slime, Hero Class
create inheritanced PoisonSlime, SuperHero
condition.
PoisonSlime attack Hero/SuperHero, damage -10, +hero.hp * 0.2 Damage
feat2 : define animal/ vegicle/ library class
Made puml class diagram
=> 240312_34_한정은

lib/24_03_07/main.dart, lib/24_03_11/wand.dart, lib/24_03_11/wizard.dart, lib/24_03_12/animal.dart, lib/24_03_12/animal_diagram.puml, lib/24_03_12/bird.dart, lib/24_03_12/book.dart, lib/24_03_12/book.puml, lib/24_03_12/dog.dart, lib/24_03_12/dot_and_square.dart, lib/24_03_12/hero.dart, lib/24_03_12/poison_slime.dart, lib/24_03_12/rabbit.dart, lib/24_03_12/slime.dart, lib/24_03_12/slime.puml, lib/24_03_12/square_diagram.puml, lib/24_03_12/vehicle.dart, lib/24_03_12/vehicle_diagram.puml, test/24_03_11/wand_test.dart
- 상속받는 클래스를 만들고 서로의 관계를 uml 로 만들어봅니다.
- Slime 클래스를 상속받는 PoisonSlime 만들기
- Book 클래스를 상속받는 NonFiction, Fiction 클래스 만들기
- Vehicle 클래스를 상속받는 Car, Truck, Motorcycle 클래스 만들기
- Animal 클래스를 상속받는 Bird, Rabbit, Dog 클래스 만들기
=> 240312_14_송윤지

lib/24_03_12/00_poisonslime.dart, lib/24_03_12/hero.dart, lib/24_03_12/inheritance practice/00_personanimal.dart, lib/24_03_12/inheritance practice/00_personanimal.puml, lib/24_03_12/inheritance practice/01_rectangle.dart, lib/24_03_12/inheritance practice/01_rectangle.puml, lib/24_03_12/inheritance practice/02_vehicle.dart, lib/24_03_12/inheritance practice/02_vehicle.puml, lib/24_03_12/inheritance practice/03_book.dart, lib/24_03_12/inheritance practice/03_book.puml, lib/24_03_12/slime.dart
=> 240312_13_성효정

lib/24_03_12/animal.dart, lib/24_03_12/book.dart, lib/24_03_12/hero.dart, lib/24_03_12/point.dart, lib/24_03_12/rectangle.dart, lib/24_03_12/slime.dart, lib/24_03_12/sword.dart, lib/24_03_12/vehicle.dart, test/Wand_test.dart
new file:   lib/24_03_12/book.dart
new file:   lib/24_03_12/hero.dart
new file:   lib/24_03_12/point.dart
new file:   lib/24_03_12/rectangle.dart
new file:   lib/24_03_12/slime.dart
new file:   lib/24_03_12/sword.dart
new file:   lib/24_03_12/vehicle.dart
modified:   test/Wand_test.dart
=> 240312_31_정지원

lib/240312/practice_3/poison_slime.dart, lib/240312/practice_4/animal.dart, lib/240312/practice_4/bird.dart, lib/240312/practice_4/dog.dart, lib/240312/practice_6/bicycle.dart, lib/240312/practice_6/car.dart
=> 240313_24_장날아

lib/240313/asset.dart, lib/240313/book.dart, lib/240313/computer.dart, lib/240313/diagrams/asset.puml, lib/240313/intangibleAsset.dart, lib/240313/patent.dart, lib/240313/tangibleAsset.dart, lib/240313/thing.dart, test/240313/test_asset.dart
=> 240313_15_송진섭

lib/24_03_13/asset.dart, lib/24_03_13/book.dart, lib/24_03_13/computer.dart, lib/24_03_13/tangible_asset.dart, lib/24_03_13/thing.dart, lib/24_03_13/uml/practice.puml, test/24_03_13/book_test.dart, test/24_03_13/computer_test.dart
추상클래스, 인터페이스 연습문제에 대한 코드 및 UML 작성
1. Asset 클래스 작성
2. TangibleAsset 클래스 작성
3. Book 클래스 작성
4. Computer 클래스 작성
5. Thing 인터페이스 작성
+ 공통사항
과제에 사용한 클래스 UML 작성
행위로 상태를 변환시키거나 값을 반환하는 클래스 메소드에 한해 테스트코드 작성
+ Computer
+ Book
=> 240313_12_성종호

lib/240312/slime.dart, lib/240312/super_hero.dart, lib/240313/asset.dart, lib/240313/book.dart, lib/240313/computer.dart, lib/240313/diagram.puml, lib/240313/intangibleAsset.dart, lib/240313/patent.dart, lib/240313/tangibleAsset.dart, lib/240313/thing.dart
feat : 구조 정의 및 class diagram 정의
=> 240313_34_한정은

lib/24_03_13/asset.dart, lib/24_03_13/book.dart, lib/24_03_13/computer.dart, lib/24_03_13/intangible_asset.dart, lib/24_03_13/patent.dart, lib/24_03_13/tangible_asset.dart, lib/24_03_13/thing.dart, lib/24_03_13/thing_asset.puml
Book, Computer 클래스 작성
TangibleAsset 클래스 작성, 위 클래스들 수정
Asset 클래스 작성
Thing 인터페이스 작성
TangibleAsset 클래스 수정, getter/setter 추가
IntangibleAsset 클래스 작성
Patent 클래스 작성
UML 작성
=> 240313_06_김형민 연습문제

lib/0313/asset.dart, lib/0313/book.dart, lib/0313/computer.dart, lib/0313/intangible_asset.dart, lib/0313/patent.dart, lib/0313/tangible_asset.dart, lib/0313/thing.dart, test/0313/computer_test.dart, test/0313/patent_test.dart
- type(유/무형), name 필드의 값은 변경되지 않지만, value 필드의 값은 시간이 지남에 따라 가치가 상승 또는 하락할 수 있기 때문에 final 키워드를 사용하지 않았습니다.
- type, name 필드는 모든 유/무형 객체가 가질 수 있는 속성이기 때문에 가장 상위에 있는 Asset 추상 클래스에 선언했습니다.
- 유형이든 무형이든 자산이라면 경제적 가치를 가지기 때문에 value 필드를 가장 상위에 있는 Asset 추상 클래스에 선언했습니다.
- weight, color 필드는 실체가 있는 유형 자산만이 가질 수 있는 속성이기 때문에 TangibleAsset 추상 클래스에 선언했습니다.
- 문제에서 weight 필드에 대한 getter/setter가 필요하다는 요구사항이 있어서 private으로 선언했습니다. getter/setter가 필요하다는 것은 필드가 public이 아니기 때문입니다.
=> 240313_21_이서우

lib/24_03_07/main.dart, lib/24_03_12/book.dart, lib/24_03_12/hero.dart, lib/24_03_12/slime.dart, lib/24_03_13/Intangible_asset.dart, lib/24_03_13/asset.dart, lib/24_03_13/asset.puml, lib/24_03_13/computer.dart, lib/24_03_13/tangible_asset.dart, lib/24_03_13/thing.dart
---- 
- 추상 클래스를 만들어 상속을 합니다.
- 인터페이스를 만들어 구현 해 봅니다.
=> 240313_14_송윤지

lib/240313/prob1.dart, lib/240313/prob2.dart, lib/240313/prob2_uml.puml, lib/240313/prob34.dart
-추상클래스
-인터페이스
-uml실패 (뭔가를 다시 깔아야하는건가?)
=> 240313_04_김윤아

lib/24_03_13/abstract/tangible_asset.dart, lib/24_03_14/practice_3.dart, lib/24_03_14/starcraft_uml.puml
- 13일 과제 수정
- 연습문제 3번 프로그램 작성
- UML 과제 작성
=> 240314_25_전성수

lib/24_03_14/01_test.dart
=> 240314_03_김세진

lib/240313/asset.puml, lib/240313/book.dart, lib/240313/computer.dart, lib/240313/tangible_asset.dart, lib/240314/Starcraft.puml, lib/240314/polymorphism_exam1.dart, lib/240314/polymorphism_exam1.puml, lib/240314/tzp_game.puml
다형성 이용
인스턴스 생성 후 불러올 수 있는 메소드 확인
List 사용 같은 메소드 호출
---
다시 수정하였습니다;;;
=> 240314_18_양혜영

lib/24_03_14/a.dart, lib/24_03_14/b.dart, lib/24_03_14/main_1.dart, lib/24_03_14/main_2.dart, lib/24_03_14/main_3.dart, lib/24_03_14/x.dart, lib/24_03_14/y.dart
new file:   lib/24_03_14/b.dart
new file:   lib/24_03_14/main_1.dart
new file:   lib/24_03_14/main_2.dart
new file:   lib/24_03_14/main_3.dart
new file:   lib/24_03_14/x.dart
new file:   lib/24_03_14/y.dart
=> 240314_31_정지원

lib/240314/polymorphism2.dart, lib/240314/polymorphism3.dart, lib/240314/starcraft diagram.puml
-리스트에 인스턴스 넣기
-클래스 컴파일 기능 확인
-스타크래프트 다이어그램
=> 240314_04_김윤아

lib/240307/slime.dart, lib/240314/_main.dart, lib/240314/charcter.dart, lib/240314/monster.dart, lib/240314/practice/polymorphism2.dart, lib/240314/practice/polymorphism3.dart, lib/240314/wizard.dart
=> 240314_01_김동혁 다형성

lib/정다희/24_03_14/quiz.dart
=> 240314_28_정다희

lib/240314/starcraft_class_diagram.puml, lib/240315/book.dart, test/240315/book_test.dart
**연습문제 1번**
- operatr ==를 오버라이드하여 title과 publishDate의 '년-월-일'이 같으면 같은 Book 인스턴스로 판단
- getFormattedDate 메소드 작성. '년-월-일' 포맷을 받아올 수 있음
**연습문제 2번***
- Book 인스턴스를 담고 있는 bookList에서 오름차순으로 sort
**연습문제 3번**
- Book 클래스에 copyWith 메소드 작성
=> 240315_08_박세훈

lib/정다희/24_03_15/excercise.dart
//제목과 출간일(2024-01-01)이 같으면 같은 책으로 판단한다
//Book 인스턴스를 담고 있는 컬렉션에 대해 sort() 를 수행하여 출간일이 오래된 순서대로 정렬한다.
//deep copy 를 위한 copyWith() 메서드를 제공한다
=> 240315_28_정다희 

lib/24_03_15/book.dart, test/24_03_15/book_test.dart
- 객체 동등성 비교
- 출간일 별 정렬
- deep copy 메서드 작성
=> 240315_25_전성수

lib/24_03_15/instance.dart
- Object 클래스의 operator와 hashCode 함수를 오버라이드 하여 재정의 해 봅니다.
- 클래스에 Comparable 인터페이스를 구현하고 sort() 함수를 오버라이드하여 재정의 해 봅니다. 
- 클래스에 copyWith 함수를 만들어봅니다.
=> 240315_14_송윤지

lib/24_03_15/book.dart, test/24_03_15/book_test.dart
인스턴스 조작
Book 클래스 작성
행위로 상태를 변환시키거나 값을 반환하는 클래스 메소드에 한해 테스트코드 작성
=> 240315_12_성종호

lib/24_03_15/practice_240315.dart
=> 240315_06_김형민 연습 문제

lib/24_03_14/practice/00_main.dart, lib/24_03_15/00_main.dart, lib/24_03_15/01_book.dart
- 비교 == override
- sort 사용
- deep copy
=> 240315_22_이필립

lib/240315/book.dart, lib/240315/book_collection.dart, lib/240315/book_deepcopy.dart, lib/test/240315/boo_deepcopy_test.dart, lib/test/240315/book_collection_test.dart, lib/test/240315/book_collection_test_ver.2.dart, lib/test/240315/book_test.dart
- Book class를 생성하고,
== 연산자를 활용하여 재정의하여 값을 비교 했다
sort()를 수행하여 오름,내림 차순으로 출력
deepCopy를 위한 copyWith()를 생성하고, 값을 비교해 보았다
=> 240315_10_변희선

lib/240314/star.plantuml, lib/240315/book.dart, lib/test/240315/book_test.dart
=> 240315_35_황태욱

lib/24_03_15/01_book.dart
**feat** : 연습문제 1, 2, 3
- object클래스 연습하기 (toString(), operator==, hashCode)
=> 240315_03_김세진

lib/0315/book.dart, test/0315/book.dart
- book 클래스를 조건에 맞게 수정했습니다.
- 의도대로 작동하는지 체크를 위한 테스트 파일을 생성했습니다.
=> 240315_19_유지영 LDT

lib/240315/book.dart, lib/240315/main.dart
feat : 타이틀과 출간일을 문자열로 변환
this book에 문자열로 반환한것과 other book에 문자열로 반환한것이 출간일이 같은지 확인
hashcode를 이용하여 같은 코드인지 확인
오래된책들로부터 비교하여 정렬
=> 240315_34_한정은

lib/0315/book.dart, test/0315/book.dart
**feat: 0315 book, test book 코드리뷰 내용 적용**
> book 클래스 파일 : 
> 1) override 된 hashCode 프로퍼티를 (년-월-일)까지만의 해시코드를 체크하도록 수정했습니다.
> book test 파일 : 
> 1) deep copy 확인 테스트 : 원본과 클론 객체 요소들의 값은 같지만 둘은 다른 객체임을 확인할 수 있는 identical 함수를 추가했습니다.   
> 2) 이름과 발행일이 다를 때 : 같을 때만을 비교했었는데, 다를 때 다른 객체로 취급하는 테스트 코드도 추가했습니다.
=> 240315_19_유지영 LDT update

lib/240313/book.dart, lib/240314/Starcraft.puml, lib/240315/book.dart, test/240315/book_test.dart
연습문제
- comparable
- sort( )
- copyWith( )
- 비교, 정렬, 깊은 복사에 대한 연습문제
=> 240315_18_양혜영 연습문제

lib/240315/practice/book.dart, test/240315/practice/book.dart
=> 240315_01_김동혁 인스턴스

lib/정다희/24_03_11/01_excersice.dart, lib/정다희/24_03_11/people.dart, lib/정다희/24_03_13/assets.dart, lib/정다희/24_03_13/thing.dart, lib/정다희/24_03_14/quiz.dart, lib/정다희/24_03_14/script.txt, lib/정다희/24_03_14/star.puml, lib/정다희/24_03_14/starcraft_team.puml
conflict 낫다고 하여 다시 pr 날렸습니다.
혹시 해결방법 알려주시면 감사하겠습니다 ;_; 아무리봐도 폴더만 추가해서 파일 추가해서.. conflict 날만한 곳을 못찾겠습니다.
=> 240311_28_정다희

lib/240315/book.dart, lib/240318/key_type.dart, lib/240318/strong_box.dart, lib/240318/word.dart, test/240315/book_test.dart, test/240318/strong_box_test.dart, test/240318/word_test.dart
- StrongBox 클래스, KeyType enum 작성
- strong_box_test 테스트 코드 작성
- Word 클래스 작성
- word_test 테스트 코드 작성
=> 240318_08_박세훈

lib/24_03_15/practice_240315.dart, lib/24_03_18/strong_box.dart, lib/24_03_18/word.dart, test/24_03_15/practice_240315_test.dart, test/24_03_18/strong_box_test.dart, test/24_03_18/word_test.dart
=> 240318_06_김형민 연습 문제

lib/24_03_15/book.dart, lib/24_03_18/key_type.dart, lib/24_03_18/strong_box.dart, lib/24_03_18/stuff.dart, lib/24_03_18/word.dart, test/24_03_15/book_test.dart, test/24_03_18/strong_box_test.dart, test/24_03_18/word_test.dart
=> 240318_25_전성수

lib/정다희/24_03_11/01_excersice.dart, lib/정다희/24_03_18/enum.dart, lib/정다희/24_03_18/exercise.dart, lib/정다희/24_03_18/num_excercise.dart, pubspec.lock, pubspec.yaml, test/24_03_15/excercise_test.dart, test/24_03_18/excercise_test.dart, test/24_03_18/num_exercise_test.dart
=> 240318_28_정다희

lib/240315/bookpractice.dart, lib/240318/strongbox.dart, lib/240318/word.dart
넘 막혀서 다른 분들거 참고해서 수정함 
모르면 외워라
=> 240318_04_김윤아

lib/24_03_18/01_strongBox.dart, lib/24_03_18/02_word.dart
=> 240318_22_이필립

lib/240315/book.dart, lib/240315/book_collection.dart, lib/240318/box.dart, lib/240318/key_type.dart, lib/240318/strong_box.dart, lib/240318/word.dart, lib/240318/word_ver2.dart, lib/test/240315/book_collection_test.dart, lib/test/240315/book_test.dart, lib/test/240318/box_test.dart, lib/test/240318/key_type_test.dart, lib/test/240318/strong_box_test.dart, lib/test/240318/word_test.dart, lib/test/240318/word_test_ver2.dart
Generic class 생성 및 enum +switch 문 활용하여 금고열기
문자열 조작으로 모음과 자음 구분하여 bool형태로 출력하기
=> 240318_10_변희선

lib/24_03_15/book.dart, lib/24_03_18/strong_box.dart, lib/24_03_18/word.dart, test/24_03_18/book_test.dart, test/24_03_18/strong_box_test.dart, test/24_03_18/word_test.dart
=> 240318_16_신승찬

lib/24_03_18/01_strong_box.dart, lib/24_03_18/02_strong_box.dart, lib/24_03_18/03_word.dart
=> 240318_03_김세진

lib/240318/00_generic.dart, lib/240318/01_enumerate.dart, lib/240318/03_string_buffer.dart, lib/240318/04_exam.dart, lib/240318/04_stopwatch.dart, lib/240318/practice/_main.dart, lib/240318/practice/key_type.dart, lib/240318/practice/strongbox.dart, lib/240318/practice/word.dart, test/240318/practice/word_test.dart
- 제네릭과 열거형
- 문자열조작
- StringBuffer
- String accessors, mutators
- 성능측정
---
StrongBox 클래스, KeyType 열거형
- StrongBox 클래스를 제네릭으로 선언
- KeyType 열거형 클래스를 enhanced enums 로 선언
Word 클래스
- isVowel 메소드 선언
- isConsonant 메소드 선언
=> 240318_01_김동혁 제네릭, 열거형, 문자열 조작

lib/24_03_15/book.dart, lib/24_03_18/is_vowel.dart, lib/24_03_18/strongbox.dart, test/24_03_15/book_test.dart, test/24_03_18/is_vowel_test.dart, test/24_03_18/strongbox_test.dart
240315 과제 오타 및 코드 수정
240318 과제 수행
=> 240318_07_박상준

lib/240318/generic/keyType.dart, lib/240318/generic/strongBox.dart, lib/240318/stringOperation/word.dart, lib/240319/department.dart, lib/240319/employee.dart, lib/240319/exception.dart, lib/240319/file.dart, test/240318/generic/strongBox.dart, test/240319/test_exception.dart, test/240319/test_file.dart, test/240319/test_json.dart
=> 240319_15_송진섭

lib/240319/quiz_1.dart, lib/240319/quiz_2.dart, lib/240319/quiz_3-1.dart, lib/240319/quiz_3.dart, test/240319/test.dart
feat : employee, department class 생성
인스턴스 생성 Json 메서드 파일 쓰기 company.txt 파일 생성
=> 240319_34_한정은

lib/24_03_19/01_exception.dart, lib/24_03_19/02_file.dart, lib/24_03_19/03_employee.dart, test/24_03_19/02_file_test.dart, test/24_03_19/03_employee_test.dart
- 예외 연습문제
- 파일 조작 연습문제, 테스트코드 작성
- 여러가지 데이터 형식 연습문제, 테스트코드 작성
=> 240319_03_김세진

lib/240318/practice_more.dart, lib/240319/file_handle.dart, lib/240319/practice_1_try_catch.dart, lib/240319/practice_2_file.dart, lib/240319/practice_3_data_type/department.dart, lib/240319/practice_3_data_type/employee.dart, test/lib/240319/practice_1_try_catch_test.dart, test/lib/240319/practice_2_file_test.dart, test/lib/240319/practice_3_data_type/department.dart
=> 240319_24_장날아

lib/24_03_18/strong_box.dart, lib/24_03_18/word.dart, lib/24_03_19/data_formats/data_formats.dart, lib/24_03_19/data_formats/department.dart, lib/24_03_19/data_formats/employee.dart, lib/24_03_19/exception/exception.dart, lib/24_03_19/file_manipulation/file_manipulation.dart, test/24_03_18/word_test.dart, test/24_03_19/data_format_test.dart, test/24_03_19/file_manipulation_test.dart
=> 240319_06_김형민 연습 문제

lib/24_03_19/Various data types.dart, lib/24_03_19/company.txt, lib/24_03_19/exception.dart, lib/24_03_19/file.dart
- 예외처리 try-catch문 사용해보기
- 파일 읽고 쓰기 
- 클래스 데이터 json 형태로 직렬화, 역직렬화 해보기
=> 240319_14_송윤지

lib/240319/regular_expression.dart, lib/240320/trader.dart, pubspec.lock, pubspec.yaml, test/240320/trader_test.dart
**연습문제 1~8 작성**
- collection 패키지 추가
- trader.dart 작성(Trader 클래스, Transaction 클래스)
- trader_test.dart 테스트 코드 작성
=> 240320_08_박세훈

lib/240320/debug_sample.dart, lib/240320/funtcion.dart, pubspec.lock, pubspec.yaml, test/240320/test_funtcion.dart
Feat: 13일차 과제
13일차 과제및 테스트코드 작성
=> 240320_15_송진섭

lib/240320_homework/query.dart, lib/240320_homework/summary.dart, pubspec.lock, pubspec.yaml, test/240320_homework/query_test.dart
feat: added query files and test code
<details><summary>세부 내용</summary>
- query 연습문제
- query 테스트 코드 작성
</details> 
<details><summary>알게 된 것</summary>
- .sorted vs ..sort의 차이를 알게되었다. List vs void!
- Iterable과 List의 차이를 알게되었다. Iterable이 더 큰 개념~
- void가 리턴되면 변수에 할당이 안된다.
</details>
=> 240320_17_신예진

lib/240319/copy.dart, lib/240319/employee.dart, lib/240320/debuging.dart, lib/240320/query.dart, lib/test/240320/debuging_test.dart, lib/test/240320/query_test.dart, pubspec.lock, pubspec.yaml
query 연습문제를 고계 함수를 사용하여, 테스트 코드 작성
=> 240320_10_변희선

lib/24_03_20/query.dart, pubspec.lock, pubspec.yaml, test/24_03_19/data_format_test.dart, test/24_03_20/query_test.dart
=> 240320_06_김형민 연습문제

lib/240319/company.dart, lib/240319/company.txt, lib/240320/query.dart, lib/test/240319/company_test.dart, lib/test/240320/query_test.dart, pubspec.lock, pubspec.yaml
query 파일 생성 
-  1. 2011년에 일어난 모든 트랜잭션을 찾아 가격 기준 오름차순으로 정리하여 이름을 나열하시오 
- 2. 거래자가 근무하는 모든 도시를 중복 없이 나열하시오
- 3. 케임브리지에서 근무하는 모든 거래자를 찾아서 이름순으로 정렬하여 나열하시오
- 4. 모든 거래자의 이름을 알파벳순으로 정렬하여 나열하시오
- 5.  밀라노에 거래자가 있는가?
- 6. 케임브리지에 거주하는 거래자의 모든 트랙잭션값을 출력하시오
- 7. 전체 트랜잭션 중 최대값은 얼마인가?
- 8. 전체 트랜잭션 중 최소값은 얼마인가?
=> 240320_35_황태욱

lib/24_03_20/01_trader.dart, test/24_03_20/01_trader_test.dart
- 고계함수(higher-order function)을 이용한 Query 연습문제 풀이
- 연습문제 풀이 테스트 코드
=> 240320_03_김세진

lib/240320/query.dart, pubspec.lock, pubspec.yaml, test/240320/test.dart
=> 240320_34_한정은

lib/24_03_20/query.dart, lib/24_03_20/trader.dart, lib/24_03_20/transaction.dart, pubspec.lock, pubspec.yaml, test/24_03_20/query.dart
람다 과제
Trader, Transaction, Query 클래스 작성
Collection 의존성 추가
행위로 상태를 변환시키거나 값을 반환하는 클래스 메소드에 한해 테스트코드 작성
=> 240320_12_성종호

lib/240320/practice/query.dart, pubspec.lock, pubspec.yaml
=> 240320_01_김동혁 함수, 람다식

lib/24_03_18/strongBox.dart, lib/24_03_18/strongBoxMain.dart, lib/24_03_21/file.dart, lib/24_03_21/get_movie_info.dart, lib/24_03_21/movie.dart, lib/24_03_21/time_out.dart, test/movie_test.dart, test/strongBoxMain_test.dart, test/time_out_test.dart
비동기적 파일 처리
직렬화 역직렬화 
timeout 시간제한
=> 240321_32_최지원

lib/240320/trader.dart, lib/240320/transaction.dart, test/240320/transaction_test.dart
query 문제풀이 
디버깅은 보지도 못함 
주말에 볼 예정 ..
=> 240320_04_김윤아

lib/240320/debug_sample.dart, lib/240321/movie.dart, lib/240321/practice1.dart, lib/240321/practice2.dart, lib/240321/practice3.dart, test/240321/test_practice1.dart, test/240321/test_practice2.dart, test/240321/test_practice3.dart
=> 240321_15_송진섭

lib/24_03_21/practice_1/file_async.dart, lib/24_03_21/practice_2/api_call.dart, lib/24_03_21/practice_3/time_out.dart
1. 파일처리
2. API 호출 및 데이터 처리
3. 타임아웃 처리
=> 240321_06_김형민 연습 문제

lib/24_03_21/01_find_file.dart, lib/24_03_21/02_movie.dart, lib/24_03_21/03_timeout_future.dart, test/24_03_21/01_find_file_test.dart, test/24_03_21/02_movie_test.dart, test/24_03_21/03_timeout_future_test.dart
1. 파일 처리
2. API 호출 및 데이터 처리
3. 타임아웃 처리
=> 240321_03_김세진

lib/24_03_21/01_async_await.dart, lib/24_03_21/02_api.dart, lib/24_03_21/03_timeout.dart
1. 파일처리
2.  API 호출 및 데이터 처리
3. 타임아웃 처리
=> 240321_13_성효정

lib/240315/book.dart, lib/240319/department.dart, lib/240320/debuging.dart, lib/240321/movie.dart, lib/fetchdata/adress.dart, lib/fetchdata/company.dart, lib/fetchdata/data.dart, lib/fetchdata/main.dart, lib/fetchdata/user.dart, pubspec.lock, pubspec.yaml, test/240315/book_test.dart, test/240319/serialization_test.dart, test/240321/file_manager_test.dart
feedback 주신 대로 수정한 부분 및
Serialization 혼자 연습한 내용 입니다.
25일 과제와 구분하기 위해서 미리 요청드립니다.
=> 240324_33_한정만 

lib/24_03_20/debugging/data_parsing.dart, lib/24_03_21/csv/csv_handling.dart, lib/24_03_21/movie/movie.dart, lib/24_03_25/DTO/stock_info.dart, lib/24_03_25/DTO/todo.dart, lib/24_03_25/DTO/todo_list.dart, lib/24_03_25/DTO/user.dart, lib/24_03_25/data_source/stock_api.dart, lib/24_03_25/data_source/todo_api.dart, lib/24_03_25/data_source/user_api.dart, lib/24_03_25/utility/network_error.dart, lib/24_03_25/utility/network_manager.dart, pubspec.lock, pubspec.yaml, test/24_03_25/data_source/stock_api_test.dart, test/24_03_25/data_source/todo_api_test.dart, test/24_03_25/data_source/user_api_test.dart
- 필수 문제 1 ~ 3번 완료
- 선택 문제 5번 완료 
- NetworkManager singleton으로 구현(연습)
- 선생님! 5번 문제를 진행하면서, Csv를 List로 전환해서 DTO에 맵핑을 할 때, List로 내려오다 보니 인덱싱을 통한 맵핑말고는 방법이 안보이던데 혹시 다른 방법이 있을까요? 
```dart
Stock.fromCsv(List<dynamic> json)
: symbol = json[0],
name = json[1],
exchange = json[2],
assertType = json[3],
ipoDate = json[4],
delistingDate = json[5],
status = json[6];
```
=> 240325_25_전성수

lib/240321/practice1.dart, lib/240321/practice2.dart, lib/240321/practice3.dart, lib/240325/address.dart, lib/240325/geo.dart, lib/240325/stock.dart, lib/240325/subway.dart, lib/240325/todo.dart, lib/240325/user.dart, lib/data_source/stock_api.dart, lib/data_source/subway_api.dart, lib/data_source/todo_api.dart, lib/data_source/user_api.dart, pubspec.lock, pubspec.yaml, test/240321/test_practice1.dart, test/240321/test_practice2.dart, test/240321/test_practice3.dart, test/240325/test_practice1.dart, test/240325/test_practice2.dart, test/240325/test_practice3.dart, test/240325/test_practice4.dart, test/240325/test_practice5.dart
=> 240325_15_송진섭

lib/240325/00_http.dart, lib/240325/practice/address.dart, lib/240325/practice/company.dart, lib/240325/practice/geo.dart, lib/240325/practice/todo.dart, lib/240325/practice/user.dart, lib/data_source/todo_api.dart, lib/data_source/user_api.dart, pubspec.lock, pubspec.yaml, test/240325/practice/todo_test.dart, test/240325/practice/user_test.dart
- Todo json 데이터 변환  
- Todo 데이터 클래스 선언  
- Todo 클래스 테스트 코드 작성  
- User json list 변환  
- User 데이터 클래스 작성  
- Address 데이터 클래스 작성  
- Geo 데이터 클래스 작성  
- Company 데이터 클래스 작성
- User 테스트 코드 작성
=> 240325_01_김동혁 DataSource

lib/24_03_25/01_user.dart, lib/24_03_25/02_todo.dart, lib/24_03_25/data_source/todo_api.dart, lib/24_03_25/data_source/user_api.dart, test/24_03_25/01_todo_api_test.dart, test/24_03_25/02_todo_api_test.dart, test/24_03_25/03_user_api_test.dart
feat : 데이터소스(JSON)을 활용하여 데이터 클래스 변환하기
- Json List를 List<Todo>형태로 변환
- Json List를 List<User>형태로 변환
=> 240325_03_김세진

lib/240320/debuging.dart, lib/240321/file.dart, lib/240321/movie.dart, lib/240325/dart_source/time_api.dart, lib/240325/dart_source/todo_api.dart, lib/240325/dart_source/user_api.dart, lib/240325/data_source.dart, lib/240325/time.dart, lib/240325/todo.dart, lib/240325/user.dart, lib/test/240321/time_out_test.dart, lib/test/240325/time_test.dart, lib/test/240325/todo_test.dart, lib/test/240325/user_test.dart, pubspec.lock, pubspec.yaml
연습문제 1~ 3 번 풀이
1. 간단한 JSON 을 데이터 클래스로 변환
2. Json List 를 List<Todo> 로 변환  
3. 복잡한 Json List 를 List 로 변환  
4. time 풀이
=> 240325_10_변희선

lib/24_03_21/api_request.dart, lib/datasource/dt_todo.dart, lib/datasource/dt_user.dart, lib/datasource/todo_api.dart, lib/datasource/user_api.dart, pubspec.lock, pubspec.yaml, test/24_03_21/movie.dart, test/24_03_25/dt_company.dart, test/24_03_25/dt_todo.dart, test/24_03_25/dt_user.dart, test/24_03_25/todo_api_request.dart, test/24_03_25/user_api_request.dart
=> 240325_27_전종현

lib/24_03_21/02_api.dart, lib/24_03_25/01_todo.dart, lib/24_03_25/02_user.dart, lib/24_03_25/03_address.dart, lib/24_03_25/04_geo.dart, lib/24_03_25/05_company.dart, lib/data_source/todo_api.dart, lib/data_source/user_api.dart, pubspec.lock, pubspec.yaml, test/data_source/todo_api_test.dart, test/data_source/user_api_test.dart
=> 240325_22_이필립

lib/240321/quiz_1.dart, lib/240321/quiz_2.dart, lib/240325/data_source/address.dart, lib/240325/data_source/company.dart, lib/240325/data_source/todo.dart, lib/240325/data_source/todo_api.dart, lib/240325/data_source/user.dart, lib/240325/data_source/user_api.dart, pubspec.lock, pubspec.yaml, test/240325/test.dart
=> 240325_34_한정은

lib/24_03_20/debug_practice1.dart, lib/24_03_21/file_practice.dart, lib/24_03_25/todo.dart, lib/24_03_25/user.dart, lib/data_source/todo_api.dart, lib/data_source/user_api.dart, lib/http/http_service.dart, pubspec.lock, pubspec.yaml, test/24_03_25/api_test.dart
##작업 내용
- api 호출로 받은 데이터를 모델 클래스로 파싱
=> 240325_14_송윤지

lib/24_03_25/address.dart, lib/24_03_25/company.dart, lib/24_03_25/geo.dart, lib/24_03_25/todo.dart, lib/24_03_25/user.dart, lib/data_source/todo_api.dart, lib/data_source/user_api.dart
=> 240325_13_성효정

lib/24_03_25/DTO/user.dart, lib/24_03_25/data_source/todo_api.dart, lib/24_03_25/data_source/user_api.dart, lib/24_03_26/data_source/album_api.dart, lib/24_03_26/data_source/comment_api.dart, lib/24_03_26/data_source/photo_api.dart, lib/24_03_26/data_source/post_api.dart, lib/24_03_26/model/album.dart, lib/24_03_26/model/comment.dart, lib/24_03_26/model/photo.dart, lib/24_03_26/model/post.dart, lib/24_03_26/repository/implements/album_repository_impl.dart, lib/24_03_26/repository/implements/comment_repository_impl.dart, lib/24_03_26/repository/implements/photo_repository_impl.dart, lib/24_03_26/repository/implements/post_repository_impl.dart, lib/24_03_26/repository/implements/todo_repository_impl.dart, lib/24_03_26/repository/implements/user_repository_impl.dart, lib/24_03_26/repository/interface/album_repository.dart, lib/24_03_26/repository/interface/comment_repository.dart, lib/24_03_26/repository/interface/photo_repository.dart, lib/24_03_26/repository/interface/post_repository.dart, lib/24_03_26/repository/interface/todo_repository.dart, lib/24_03_26/repository/interface/user_repository.dart, test/24_03_25/data_source/user_api_test.dart, test/24_03_26/repository/implements/album_repository_impl_test.dart, test/24_03_26/repository/implements/comment_repository_impl_test.dart, test/24_03_26/repository/implements/photo_repository_impl.dart, test/24_03_26/repository/implements/post_repository_impl_test.dart, test/24_03_26/repository/implements/todo_repository_impl.dart, test/24_03_26/repository/implements/user_repository_impl.dart
- 필수 과제 1 ~ 5번 완료
- 선택 과제 6번 완료
=> 240326_25_전성수

lib/24_03_25/subways/subway_info.dart, lib/24_03_26/model/album.dart, lib/24_03_26/model/comment.dart, lib/24_03_26/model/photo.dart, lib/24_03_26/model/post.dart, lib/24_03_26/model/todo.dart, lib/24_03_26/model/user_related/address.dart, lib/24_03_26/model/user_related/company.dart, lib/24_03_26/model/user_related/geo.dart, lib/24_03_26/model/user_related/user.dart, lib/24_03_26/repository/album_repo_impl.dart, lib/24_03_26/repository/album_repository.dart, lib/24_03_26/repository/comment_repo_impl.dart, lib/24_03_26/repository/comment_repository.dart, lib/24_03_26/repository/photo_repo_impl.dart, lib/24_03_26/repository/photo_repository.dart, lib/24_03_26/repository/post_repo_imple.dart, lib/24_03_26/repository/post_repository.dart, lib/24_03_26/repository/todo_repo_impl.dart, lib/24_03_26/repository/todo_repository.dart, lib/24_03_26/repository/user_repo_impl.dart, lib/24_03_26/repository/user_repository.dart, test/24_03_26/album_test.dart, test/24_03_26/comment_test.dart, test/24_03_26/photo_test.dart, test/24_03_26/post_test.dart, test/24_03_26/todo_test.dart, test/24_03_26/user_test.dart
1. comment
2. album
3. photo
4. todo
5. user
6. post
=> 240326_06_김형민 연습 문제

lib/240326/datamodel/memo.dart, lib/240326/repository/memoRepository.dart, test/240326/test_main.dart
=> 240326_15_송진섭

lib/24_03_26/data_source/task1_comment_api.dart, lib/24_03_26/data_source/task2_album_api.dart, lib/24_03_26/data_source/task3_photo_api.dart, lib/24_03_26/data_source/task4_todo_api.dart, lib/24_03_26/data_source/task5_user_api.dart, lib/24_03_26/interfaces/task1_comment_repository_interface.dart, lib/24_03_26/interfaces/task2_album_repository_interface.dart, lib/24_03_26/interfaces/task3_photo_repository_interface.dart, lib/24_03_26/interfaces/task4_todo_repository_interface.dart, lib/24_03_26/interfaces/task5_user_repository_interface.dart, lib/24_03_26/model_class/task1_comment.dart, lib/24_03_26/model_class/task2_album.dart, lib/24_03_26/model_class/task3_photo.dart, lib/24_03_26/model_class/task4_todo.dart, lib/24_03_26/model_class/task5_address.dart, lib/24_03_26/model_class/task5_company.dart, lib/24_03_26/model_class/task5_geo.dart, lib/24_03_26/model_class/task5_user.dart, lib/24_03_26/repository/task1_comment_repository.dart, lib/24_03_26/repository/task2_album_repository.dart, lib/24_03_26/repository/task3_photo_repository.dart, lib/24_03_26/repository/task4_todo_repository.dart, lib/24_03_26/repository/task5_user_repository.dart, test/24_03_26/task1_comment_respository_test.dart, test/24_03_26/task2_album_repository_test.dart, test/24_03_26/task3_photo_repository_test.dart, test/24_03_26/task4_todo_repository_test.dart, test/24_03_26/task5_user_repository_test.dart
=> 240326_07_박상준

lib/240326/data_source/album_api.dart, lib/240326/data_source/comments_api.dart, lib/240326/data_source/photo_api.dart, lib/240326/data_source/todo_api.dart, lib/240326/data_source/user_api.dart, lib/240326/model/address.dart, lib/240326/model/album.dart, lib/240326/model/comment.dart, lib/240326/model/company.dart, lib/240326/model/photo.dart, lib/240326/model/todo.dart, lib/240326/model/user.dart, lib/240326/repository/album_repository.dart, lib/240326/repository/album_repository_implements.dart, lib/240326/repository/comment_repository.dart, lib/240326/repository/comment_repository_implements.dart, lib/240326/repository/photo_repository.dart, lib/240326/repository/photo_repository_implements.dart, lib/240326/repository/todo_repository.dart, lib/240326/repository/todo_repository_implements.dart, lib/240326/repository/user_repository.dart, lib/240326/repository/user_repository_implements.dart, test/240326/test.dart
=> 240326_34_한정은

lib/240325/address.dart, lib/240325/data_source/todo_api.dart, lib/240325/data_source/user_api.dart, lib/240325/geo.dart, lib/240325/todo.dart, lib/240325/user.dart, lib/240326/data_source/album_api.dart, lib/240326/data_source/comments_api.dart, lib/240326/data_source/photo_api.dart, lib/240326/data_source/post_api.dart, lib/240326/datamodel/album.dart, lib/240326/datamodel/comment.dart, lib/240326/datamodel/photo.dart, lib/240326/datamodel/post.dart, lib/240326/repository/albumRepository.dart, lib/240326/repository/albumRepositoryImpl.dart, lib/240326/repository/commentsRepository.dart, lib/240326/repository/commentsRepositoryImpl.dart, lib/240326/repository/photoRepository.dart, lib/240326/repository/photoRepositoryImpl.dart, lib/240326/repository/postRepository.dart, lib/240326/repository/postRepositoryImpl.dart, lib/240326/repository/toDoRepository.dart, lib/240326/repository/toDoRepositoryImpl.dart, lib/240326/repository/userRepository.dart, lib/240326/repository/userRepositoryImpl.dart, pubspec.lock, pubspec.yaml, test/240326/test_practice.dart
=> 240326_04_김윤아

lib/24_03_26/data_source/album_api.dart, lib/24_03_26/data_source/comment_api.dart, lib/24_03_26/data_source/photo_api.dart, lib/24_03_26/data_source/todo_api.dart, lib/24_03_26/data_source/user_api.dart, lib/24_03_26/implements/album_impl.dart, lib/24_03_26/implements/comment_impl.dart, lib/24_03_26/implements/photo_impl.dart, lib/24_03_26/implements/todo_impl.dart, lib/24_03_26/implements/user_impl.dart, lib/24_03_26/model_class/00_comment_class.dart, lib/24_03_26/model_class/01_album_class.dart, lib/24_03_26/model_class/02_photo_class.dart, lib/24_03_26/model_class/03_todo_class.dart, lib/24_03_26/repository/00_comment_repository.dart, lib/24_03_26/repository/01_album_repository.dart, lib/24_03_26/repository/02_photo_repository.dart, lib/24_03_26/repository/03_todo_repository.dart, lib/24_03_26/repository/04_user.dart
=> 240326_13_성효정

lib/24_03_26/data_source/album_api.dart, lib/24_03_26/data_source/comment_api.dart, lib/24_03_26/data_source/photo_api.dart, lib/24_03_26/data_source/todo_api.dart, lib/24_03_26/data_source/user_api.dart, lib/24_03_26/model/album.dart, lib/24_03_26/model/comment.dart, lib/24_03_26/model/photo.dart, lib/24_03_26/model/todo.dart, lib/24_03_26/model/user_model/address.dart, lib/24_03_26/model/user_model/company.dart, lib/24_03_26/model/user_model/geo.dart, lib/24_03_26/model/user_model/user.dart, lib/24_03_26/repository/album_repository_impl.dart, lib/24_03_26/repository/album_ropository.dart, lib/24_03_26/repository/comment_repository.dart, lib/24_03_26/repository/comment_repository_impl.dart, lib/24_03_26/repository/photo_repository.dart, lib/24_03_26/repository/photo_repository_impl.dart, lib/24_03_26/repository/todo_repository.dart, lib/24_03_26/repository/todo_repository_impl.dart, lib/24_03_26/repository/user_repository.dart, lib/24_03_26/repository/user_repository_impl.dart, test/24_03_26/album_test.dart, test/24_03_26/comment_test.dart, test/24_03_26/photo_test.dart, test/24_03_26/todo_test.dart, test/24_03_26/uesr_test.dart
=> 240326_22_이필립

lib/24_03_20/debug_practice1.dart, lib/24_03_26/album.dart, lib/24_03_26/comment.dart, lib/24_03_26/photo.dart, lib/24_03_26/post.dart, lib/data_source/album_api.dart, lib/data_source/comment_api.dart, lib/data_source/photo_api.dart, lib/data_source/post_api.dart, lib/data_source/todo_api.dart, lib/data_source/user_api.dart, lib/http/http_service.dart, lib/repository/album_repository.dart, lib/repository/album_repository_impl.dart, lib/repository/comment_repository.dart, lib/repository/comment_repository_impl.dart, lib/repository/photo_repository.dart, lib/repository/photo_repository_impl.dart, lib/repository/post_repository.dart, lib/repository/post_repository_impl.dart, lib/repository/todo_repository.dart, lib/repository/todo_repository_impl.dart, lib/repository/user_repository.dart, lib/repository/user_repository_impl.dart, test/24_03_25/api_test.dart, test/24_03_26/repository_test.dart
- Repository 인터페이스 클래스 작성 후 인터페이스 구현한 Repository 클래스를 만들어 데이터 핸들링 함수 작성
=> 240326_14_송윤지

lib/240327/bark.dart, lib/240327/data_source/mask_api.dart, lib/240327/factorial.dart, lib/240327/listfun.dart, lib/240327/model/store.dart, lib/240327/palindrome.dart, lib/240327/repository/maskRepository.dart, lib/240327/repository/maskRepositoryImpl.dart, test/240327/test_MaskRepository.dart, test/240327/test_bank.dart, test/240327/test_factorial.dart, test/240327/test_listfun.dart, test/240327/test_palindrome.dart
=> 240327_15_송진섭

lib/24_03_27/data_source/mask_store_api.dart, lib/24_03_27/model/bank.dart, lib/24_03_27/model/mask_store.dart, lib/24_03_27/repository/implements/mask_store_repository_impl.dart, lib/24_03_27/repository/interface/mask_store_repository.dart, lib/24_03_27/top_level_method.dart, test/24_03_27/implements/mask_store_repository_impl_test.dart, test/24_03_27/model/bank_test.dart, test/24_03_27/top_level_method_test.dart
- 필수문제 1 ~ 5번 완료
<br><br>
- 선생님 5번 과제 진행하면서, MockClient를 사용하면서 인코딩 문제로 조금 고통받았는데, 다른게 아니라 Response의 headers 값을 설정해줄때 일반적인 방법으로는 안되고, HttpHeaders 라는 추상 클래스를 사용해서 값을 넣으니까 정상 동작 하더라구요!
HttpHeaders 문서를 읽어보니 ClientResponse는 항상 불변의 헤더값을 가진다 이런말이 있던데 무슨말인지 이해가안가서, 왜 일반적인 방법으로는 동작을 안하는지가 궁금합니다.
```dart
//HttpHeaders 클래스 사용 
final mockClient = MockClient((request) async {
if (request.url.toString() == 'http://104.198.248.76:3000/mask') {
return http.Response(jsonString, 200, headers: {
HttpHeaders.contentTypeHeader: 'application/json; charset=utf-8'
});
}
return http.Response('''{"message":"잘못된 요청"}''', 400);
});
//제가 아는 기본적인 header 값 세팅방법
final mockClient = MockClient((request) async {
if (request.url.toString() == 'http://104.198.248.76:3000/mask') {
return http.Response(jsonString, 200, …
```
=> 240327_25_전성수

lib/0327/bank.dart, lib/0327/data_source/mask_api.dart, lib/0327/factorial.dart, lib/0327/model/mask.dart, lib/0327/model/store.dart, lib/0327/palindrome.dart, lib/0327/repository/mask_repository.dart, lib/0327/repository/mask_repository_impl.dart, lib/0327/two_max_number.dart, test/0327/bank_test.dart, test/0327/factorial_test.dart, test/0327/mask_test.dart, test/0327/palindrome_test.dart, test/0327/two_max_number_test.dart
1. fromJson named constructor의 initializer list에서 JSON의 key와 일치하지 않은 값을 map의 key로 사용하고 있습니다. 존재하지 않는 key로 value를 찾을 수 없습니다.
2. 만약 phone의 value가 문자가 아닌 숫자로 전달될 경우 as String으로 형변환을 시도하게 되면 exception이 발생합니다.
3. toJson method에서 map을 생성할 때 사용되는 key에 오자와 탈자가 있습니다. 생성 및 반환에는 문제가 없지만 데이터를 수신하는 측에서 문제가 발생할 수 있습니다.
문자열의 첫 번째 인덱스(p1)와 마지막 인덱스(p2)를 가리키는 포인터 변수를 만들었습니다.
p1은 1씩 증가시키고 p2는 1씩 감소시키며 포인터 변수가 가리키는 값끼리 비교합니다.
양쪽 끝에서 좁혀가면서 확인하기 때문에 절반만 확인하지만 시간복잡도는 O(n/2) -> O(n)입니다. 상수 계수는 n의 크기가 커질수록 무시될 정도의 작은 값이 되어 시간복잡도에서 상수 계수는 고려하지 않기 때문입니다.
한 번이라도 값이 일치하지 않을 경우 false를 반환합니다.
리스트의 길이를 n이라고 했을 때 O(n)의 시간복잡도로 리스트에서 가장 큰 두 수를 찾을 수 있도록 1회만 순회했습니다.
리스트를 정렬해서 구할 수도 있지만 O(nlogn)의 시간복잡도를 갖게 됩니다. 원소 개수가 많지 않다면 괜찮지만 개수가 많아질수록 더 많은 시간이 소요됩니다.
int 자료형이 가질 수 있는 최솟값과 최댓값을 고려하여 두 정수를 더했을 때 오버플로우 또는 언더플로우가 발생할 경우 …
=> 240327_21_이서우

lib/240327/api/mask_api.dart, lib/240327/api/mock_mask_api.dart, lib/240327/model/bank.dart, lib/240327/model/mask.dart, lib/240327/model/store.dart, lib/240327/repository/mask_repository.dart, lib/240327/repository/mask_repository_impl.dart, test/240327/add_max_second_max_test.dart, test/240327/bank_test.dart, test/240327/bank_test.md, test/240327/factorial_test.dart, test/240327/mask_test.dart, test/240327/palindrome_test.dart
- Bank 데이터 클래스, 테스트 코드
- palindrome 함수, 테스트 코드
- addMaxAndSecondMax 함수, 테스트 코드
- factorial 함수, 테스트 코드
- Mask 데이터 클래스, Api, Repository,Repository Impl, MockApi, 테스트 코드
=> 240317_01_김동혁 단위 테스트

lib/240327/data_source/mask_api.dart, lib/240327/factorial.dart, lib/240327/model/bank.dart, lib/240327/model/mask.dart, lib/240327/repository/mask_repository.dart, lib/240327/repository/mask_repository_impl.dart, lib/240327/test3.dart, lib/240327/top_level.dart, test/240327/bank_test.dart, test/240327/factorial_test.dart, test/240327/mask_test.dart, test/240327/test3_test.dart, test/240327/top_level_test.dart
혼자 풀기 어려워서 다른 분 PR 읽어보면서 했습니다.
=> 240327_30_정성찬

lib/24_03_27/bank.dart, lib/24_03_27/factorial.dart, lib/24_03_27/mask.dart, lib/24_03_27/mask_api.dart, lib/24_03_27/mask_repositoryImpl.dart, lib/24_03_27/palindrome.dart, lib/24_03_27/stores.dart, lib/24_03_27/sumOfTopTwo.dart, test/24_03_27/algorithm_test.dart, test/24_03_27/bank_test.dart, test/24_03_27/mask_test.dart
- Mac용 안드로이드 스튜디오에서 간혹가다가 먹통? 아니면 마우스 좌클릭 비 활성화가 일어나는 것 같은데
- 그때 우클릭을 한 뒤, Capslock을 누르면 풀리는 것 같습니다. (인터넷 찾아봄), 한영 전환 때문에? 일어나는 버그인 듯 싶습니다.
- 안드로이드 스튜디오 뿐만 아니라 Jetbrains 사 제품은 다 그런것 같습니다. (WebStorm 쓸때도 당해봄)
- 물론 명확하지 않은 민간요법 같습니다.. 😅😅;; 아무튼 이제 재시작을 안해도 될 것 같습니다.
- 출처 : https://forwe.tistory.com/18
=> 240327_07_박상준

lib/240328/data_source/mask_api.dart, lib/240328/data_source/mockPhotoApi.dart, lib/240328/data_source/user_api.dart, lib/240328/dto/photo_dto.dart, lib/240328/dto/store_dto.dart, lib/240328/dto/user_dto.dart, lib/240328/enum/enum_photo.dart, lib/240328/mapper/photo_mapper.dart, lib/240328/mapper/store_mapper.dart, lib/240328/mapper/user_mapper.dart, lib/240328/model/photo.dart, lib/240328/model/store.dart, lib/240328/model/user.dart, lib/240328/repository/maskRepository.dart, lib/240328/repository/maskRepositoryImpl.dart, lib/240328/repository/photoRepository.dart, lib/240328/repository/photoRepositoryImpl.dart, lib/240328/repository/userRepository.dart, lib/240328/repository/userRepositoryImpl.dart, test/240328/test_MaskRepository.dart, test/240328/test_UserRepository.dart, test/240328/test_photoRepository.dart
=> 240328_15_송진섭

lib/24_03_27/bank.dart, lib/24_03_27/data_source/mask_api.dart, lib/24_03_27/factorial.dart, lib/24_03_27/largeSum.dart, lib/24_03_27/model/mask.dart, lib/24_03_27/model/store.dart, lib/24_03_27/palindrome.dart, lib/24_03_27/repository/mask_repository.dart, lib/24_03_27/repository/mask_repository_impl.dart, test/24_03_27/factorial_test.dart, test/24_03_27/largeSum_test.dart, test/24_03_27/mask_test.dart, test/24_03_27/palindrome_test.dart
=> 240327_22_이필립

lib/24_03_25/DTO/user.dart, lib/24_03_25/data_source/user_api.dart, lib/24_03_26/repository/implements/user_repository_impl.dart, lib/24_03_26/repository/interface/user_repository.dart, lib/24_03_27/data_source/mask_store_api.dart, lib/24_03_27/model/mask_store.dart, lib/24_03_27/repository/implements/mask_store_repository_impl.dart, lib/24_03_27/repository/interface/mask_store_repository.dart, lib/24_03_28/data_source/content_api.dart, lib/24_03_28/dto/address_dto.dart, lib/24_03_28/dto/company_dto.dart, lib/24_03_28/dto/content_dto.dart, lib/24_03_28/dto/geography_dto.dart, lib/24_03_28/dto/mask_store_dto.dart, lib/24_03_28/dto/store_dto.dart, lib/24_03_28/dto/user_dto.dart, lib/24_03_28/mapper/content_mapper.dart, lib/24_03_28/mapper/mask_store_mapper.dart, lib/24_03_28/mapper/store_mapper.dart, lib/24_03_28/mapper/user_mapper.dart, lib/24_03_28/model/content.dart, lib/24_03_28/model/name_space/media_type.dart, lib/24_03_28/repository/implements/content_repository_impl.dart, lib/24_03_28/repository/interface/content_repository.dart, test/24_03_25/data_source/user_api_test.dart, test/24_03_26/repository/implements/user_repository_impl.dart, test/24_03_27/implements/mask_store_repository_impl_test.dart, test/24_03_28/repository/implements/content_repository_impl_test.dart
- 1 ~ 3 번 완료
- 안녕하세요 선생님. 3번 과제를 진행하면서 궁금한 부분이 있습니다! fromJson을 통해서 값을 매핑할 때, 타입이 맞지않아 터지게 되어있던데 이 부분에 대한 타입 검증을 fromJson 내부에서 처리해도 괜찮은 건가요? 아래의 id 부분 입니다! 
```dart
ContentDto.fromJson(dynamic json) {
id = json['id'].runtimeType == String ? num.parse(json['id']) : json['id'];
type = json['type'];
title = json['title'];
content = json['content'];
createdAt = json['“created_at”'];
}
```
- 두 번째로, 필드값으로 다른 객체를 받는 모델의 경우, 한 파일 내에 DataClass를 다 작성해줘도 무방한가요? 일일이 파일을 분리하니 오히려 더 복잡해지는것 같아서..여쭤봅니다!! 감사합니다.
=> 240328_25_전성수

lib/240327/data_source/mask_api.dart, lib/240327/dto/mask_dto.dart, lib/240327/dto/store_dto.dart, lib/240327/mapper/mask_mapper.dart, lib/240327/mapper/store_mapper.dart, lib/240327/model/stores.dart, lib/240327/repository/mask_repo.dart, lib/240327/repository/mask_repo_impl.dart, test/240328/test.dart
=> 240328_34_한정은

lib/240327/model/stores.dart, lib/240328/data_source/mask_api.dart, lib/240328/data_source/user_api.dart, lib/240328/dto/mask_dto.dart, lib/240328/dto/store_dto.dart, lib/240328/dto/user_dto.dart, lib/240328/mapper/mask_mapper.dart, lib/240328/mapper/user_mapper.dart, lib/240328/model/address.dart, lib/240328/model/geo.dart, lib/240328/model/mask.dart, lib/240328/model/stores.dart, lib/240328/model/user.dart, lib/240328/repository/mask_repository.dart, lib/240328/repository/mask_repository_impl.dart, lib/240328/repository/user_repository.dart, lib/test/240328/stores_test.dart, lib/test/240328/user_test.dart
동적 Json 처리 연습
Model, DTO, Mapper 작성 연습
=> 240328_10_변희선
